apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-waste-app
  namespace: smart-waste
  labels:
    app: smart-waste-app
    tier: application
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: smart-waste-app
  template:
    metadata:
      labels:
        app: smart-waste-app
        tier: application
    spec:
      containers:
      - name: smart-waste-app
        image: ${ACR_NAME}.azurecr.io/smart-waste:${IMAGE_TAG}
        ports:
        - containerPort: 3000
          name: frontend
        - containerPort: 3001
          name: backend
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: smart-waste-config
              key: NODE_ENV
        - name: MONGODB_URI
          value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/$(MONGODB_DATABASE)?authSource=admin"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: smart-waste-secrets
              key: mongodb-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smart-waste-secrets
              key: mongodb-password
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: smart-waste-config
              key: MONGODB_DATABASE
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smart-waste-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: smart-waste-secrets
              key: stripe-secret-key
        - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: smart-waste-secrets
              key: stripe-publishable-key
        - name: REACT_APP_API_URL
          value: "http://smart-waste-backend:3001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: acr-secret
      securityContext:
        fsGroup: 1001
